# Generated by Django 5.0.6 on 2024-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZzDiscussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_discussions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzFriendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lik', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'zz_friendship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzHobbys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zz_hobbys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzLangages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zz_langages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'zz_medias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('pseudo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField()),
                ('last_connect', models.DateTimeField()),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=22, null=True)),
                ('plage', models.CharField(blank=True, max_length=2, null=True)),
                ('astre', models.CharField(blank=True, max_length=10, null=True)),
                ('religion', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('hobby', models.JSONField(blank=True, null=True)),
                ('pref', models.JSONField(blank=True, null=True)),
                ('online', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersDiscussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('lastdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_users_discussions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersLangages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'zz_users_langages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_users_medias',
                'managed': False,
            },
        ),
    ]
