# Generated by Django 5.0.6 on 2024-06-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zzfriendship',
            options={},
        ),
    ]
