# Generated by Django 5.0.6 on 2024-06-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondatab', '0002_alter_zzfriendship_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zzfriendship',
            options={'managed': False},
        ),
    ]
