# Generated by Django 5.0.6 on 2024-06-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zz_MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Zz_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zz_email', models.EmailField(max_length=100, unique=True)),
                ('zz_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zz_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zz_name', models.CharField(max_length=100, unique=True)),
                ('zz_prenom', models.CharField(max_length=100)),
                ('zz_date_naissance', models.DateField()),
                ('zz_sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=255)),
                ('zz_recherche', models.CharField(choices=[(0, 'homme'), (1, 'Femme'), (None, 'les deux')], max_length=255)),
                ('zz_profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('zz_additional_media', models.ManyToManyField(blank=True, to='Utilisateurs.zz_mediafile')),
                ('zz_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.zz_users')),
            ],
        ),
        migrations.AddField(
            model_name='zz_mediafile',
            name='zz_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.zz_users'),
        ),
    ]
