# Generated by Django 5.0.6 on 2024-06-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilisateursZzMediafile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Utilisateurs_zz_mediafile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilisateursZzProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zz_name', models.CharField(max_length=100, unique=True)),
                ('zz_prenom', models.CharField(max_length=100)),
                ('zz_date_naissance', models.DateField()),
                ('zz_sexe', models.CharField(max_length=255)),
                ('zz_recherche', models.CharField(max_length=255)),
                ('zz_profile_picture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Utilisateurs_zz_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilisateursZzProfileZzAdditionalMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Utilisateurs_zz_profile_zz_additional_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilisateursZzUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zz_email', models.CharField(max_length=100, unique=True)),
                ('zz_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Utilisateurs_zz_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzAstrales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zz_astrales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzDiscussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'zz_discussions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zz_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzLangages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zz_langages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzPlages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zz_plages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzProfils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('profil_user', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('oneline', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_profils',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzRelationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zz_relation_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzReligions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zz_religions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zz_sex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('pseudo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_connect', models.DateTimeField()),
            ],
            options={
                'db_table': 'zz_users',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='zz_profile',
            name='zz_additional_media',
        ),
        migrations.RemoveField(
            model_name='zz_profile',
            name='zz_user',
        ),
        migrations.CreateModel(
            name='ZzUsersAstralesPref',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilisateurs.zzusers')),
            ],
            options={
                'db_table': 'zz_users_astrales_pref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersDiscussions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilisateurs.zzusers')),
                ('status', models.IntegerField()),
                ('lastdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zz_users_discussions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersLangages',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilisateurs.zzusers')),
                ('type', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'zz_users_langages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersPlagesPref',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilisateurs.zzusers')),
            ],
            options={
                'db_table': 'zz_users_plages_pref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZzUsersReligionsPref',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilisateurs.zzusers')),
            ],
            options={
                'db_table': 'zz_users_religions_pref',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Zz_MediaFile',
        ),
        migrations.DeleteModel(
            name='Zz_profile',
        ),
        migrations.DeleteModel(
            name='Zz_Users',
        ),
    ]
