# Generated by Django 4.0 on 2024-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zz_profile',
            name='zz_additional_media',
            field=models.ManyToManyField(blank=True, to='Utilisateurs.Zz_MediaFile'),
        ),
    ]
