# Generated by Django 5.0.6 on 2024-06-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0002_alter_zz_profile_zz_additional_media'),
        ('Utilisateurs', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
    ]
